Map dictionary = <String, dynamic>{
  "b": {
    "initial": [
      "Baby",
      "Back",
      "Bacon",
      "Bag",
      "Banana",
      "Bed",
      "Boots",
      "Boy",
      "Bus",
      "Beach ball",
    ],
    "median": [
      "Cheeseburger",
      "Robot",
      "Rabbit",
      "Table",
      "Zebra",
      "Baby",
      "Newborn",
      "Sailboat",
      "Blueberries",
      "Baseball",
    ],
    "final": [
      "Crab",
      "Globe",
      "Cab",
      "Climb",
      "Crib",
      "Door knob",
      "Bathtub",
      "Bib",
      "Ice cube",
      "Robe",
    ],
  },
  "ch": {
    "median": [
      "Teacher",
      "Watching",
      "Picture",
      "Ketchup",
      "Statue",
      "Peaches",
      "Temperature",
      "Beach ball",
      "Wheelchair",
      "Nachos",
    ],
    "initial": [
      "Chair",
      "Chin",
      "Cheek",
      "Cheese",
      "Chain",
      "Children",
      "Chase",
      "Check",
      "Chess",
      "Chicken",
    ],
    "final": [
      "Peach",
      "Sandwich",
      "Match",
      "Lunch",
      "Watch",
      "Couch",
      "Coach",
      "Branch",
      "Catch",
      "March",
    ],
  },
  "d": {
    "initial": [
      "Door",
      "Dress",
      "Doughnut",
      "Driving",
      "Dice",
      "Dance",
      "Deer",
      "Dinner",
      "Dog",
      "Duck",
    ],
    "median": [
      "Hotdog",
      "Avocado",
      "Medicine",
      "Soda",
      "Radish",
      "Spider",
      "Shadow",
      "Ladder",
      "Birthday",
      "Bandage",
    ],
    "final": [
      "Sad",
      "Salad",
      "Pyramid",
      "Sword",
      "Bored",
      "Bed",
      "Mud",
      "Sand",
      "Fast Food",
      "Lemonade",
    ],
  },
  "f": {
    "initial": [
      "Five",
      "Face",
      "Factory",
      "Fall",
      "Family",
      "Fan",
      "Fast",
      "Fat",
      "Fish",
      "Finger",
    ],
    "median": [
      "Sofa",
      "Coffee",
      "Rainfall",
      "Trophy",
      "Dolphins",
      "Headphone",
      "Muffin",
      "Seafood",
      "Pacifier",
      "Waffles",
    ],
    "final": [
      "Beef",
      "Bookshelf",
      "Calf",
      "Chef",
      "Chief",
      "Cliff",
      "Cough",
      "Cream puff",
      "Elf",
      "Giraffe",
    ]
  },
  "g": {
    "initial": [
      "Goat",
      "Goose",
      "Game",
      "Gift",
      "Gum",
      "Gold",
      "Golf",
      "Guess",
      "Gas",
      "Guard",
    ],
    "median": [
      "Cougar",
      "Seagull",
      "Dragon",
      "Yoga",
      "Eggplant",
      "Magnet",
      "Juggle",
      "Jogging",
      "Eagle",
      "Tiger",
    ],
    "final": [
      "Dog",
      "Egg",
      "Bag",
      "Dig",
      "Bug",
      "Flag",
      "Leg",
      "Big",
      "Rug",
      "Pig",
    ],
  },
  "h": {
    "initial": [
      "Ham",
      "Hat",
      "Hippo",
      "Horse",
      "Heart",
      "Halloween",
      "House",
      "Hair",
      "Helicopter",
      "Hamburger",
    ],
    "median": [
      "Grasshopper",
      "Broken Heart",
      "Behind",
      "Bird House",
      "Unhappy",
      "Garden Hose",
      "Light House",
      "Hula Hoop",
      "Hedgehog",
      "Seahorse",
    ],
    // "final": [
    //   223,
    //   344,
    //   556,
    //   677,
    //   788,
    // ]
  },
  "i":{
    "initial": [
      "Ladybug",
      "Lamb",
      "Lamp",
      "Leaf",
      "Lemon",
      "Lettuce",
      "Lion",
      "Lock",
      "Lunch"
    ],
    "median":[
      "Alligator",
      "Dollar",
      "Elephant",
      "Family",
      "Melon",
      "Pillow",
      "Police",
      "Relaxing"
      "Salad"
      "Violin"
    ],
    "final":[
      "Beach Ball",
      "Bowl",
      "Camel",
      "Fall",
      "Mail",
      "Nail Polish",
      "Owl",
      "Pencil",
      "Seal",
      "Table"
    ]
  },
  "j": {
    "initial": [
      "Jeep",
      "Jogging",
      "Jump",
      "Juice",
      "Gym",
      "Jar",
      "Jeans",
      "Jello",
      "Jam",
      "Jacket",
    ],
    "median": [
      "Magic",
      "Pages",
      "Oxygen",
      "Vegetables",
      "Danger",
      "Pigeon",
      "Teenagers",
      "Hedgehog",
      "Charger",
      "Angel",
    ],
    "final": [
      "Orange",
      "Baggage",
      "Sausage",
      "Judge",
      "Badge",
      "Bridge",
      "Storage",
      "Village",
      "Package",
      "Bandage",
    ]
  },
  "k": {
    "initial": [
      "Key",
      "Can",
      "King",
      "Coin",
      "Cow",
      "Coffee",
      "Cage",
      "Camping",
      "Comb",
      "Cookies",
    ],
    "median": [
      "Bucket",
      "Toy car",
      "Haircut",
      "Pumpkin",
      "Talking",
      "Bacon",
      "Chicken",
      "Trashcan",
      "Raccoon",
      "Taco",
    ],
    "final": [
      "Book",
      "Duck",
      "Lock",
      "Sick",
      "Socks",
      "Think",
      "Beak",
      "Sink",
      "Chick",
      "Bike",
    ],
  },
  "l": {
    "initial": [
      "Lemon",
      "Lamp",
      "Leaf",
      "Lion",
      "Ladybug",
      "Left",
      "Lamb",
      "Lunch",
      "Lettuce",
      "Lock",
    ],
    "median": [
      "Alligator",
      "Salad",
      "Melon",
      "Dollar",
      "Pillow",
      "Police",
      "Family",
      "Relaxing",
      "Elephants",
      "Violin",
    ],
    "final": [
      "Pencil",
      "Fall",
      "Table",
      "Ball",
      "Seal",
      "Camel",
      "Bowl",
      "Mail",
      "Owl",
      "Shell",
    ],
  },
  "m": {
    "initial": [
      "Meat",
      "Mango",
      "Monkey",
      "Money",
      "Magnet",
      "Mat",
      "Men",
      "Mop",
      "Mountain",
      "Muffin",
    ],
    "median": [
      "Swimming",
      "Hammer",
      "Lemon",
      "Camel",
      "Climbing",
      "Llama",
      "Drummer",
      "Jasmine",
      "Camping",
      "Tomatoes",
    ],
    "final": [
      "Jam",
      "Comb",
      "Ham",
      "Broom",
      "Dream",
      "Ice cream",
      "Lambs",
      "Perfume",
      "Plum",
      "Mushroom",
    ],
  },
  "n": {
    "initial": [
      "Nose",
      "Knife",
      "Noisy",
      "Nacho",
      "Nurse",
      "Knee",
      "Nail polish",
      "Numbers",
      "Necklace",
      "Notebook",
    ],
    "median": [
      "Pencil",
      "Tennis",
      "Pancake",
      "Candy",
      "Banana",
      "Dinosaur",
      "Piano",
      "Canada",
      "Peanuts",
      "Animals",
    ],
    "final": [
      "Cabin",
      "Bacon",
      "Raccoon",
      "Pumpkin",
      "Sign",
      "Ribbon",
      "Spoon",
      "Dolphin",
      "Watermelon",
      "Train",
    ],
  },
  "p": {
    "initial": [
      "Pie",
      "Pen",
      "Peach",
      "Pants",
      "Paint",
      "Pig",
      "Peas",
      "Pot",
      "Pancake",
      "Pencil"
    ],
    "median": [
      "Backpack",
      "Camping",
      "Coupon",
      "Diaper",
      "Dustpan",
      "Grasshopper",
      "Hippo",
      "Icepack",
      "Jumping",
      "Leopard"
    ],
    "final": [
      "Cup",
      "Sheep",
      "Mop",
      "Up",
      "Wrap",
      "Soup",
      "Map",
      "Ship",
      "Jeep",
      "Cantaloup",
    ],
  },
  "R": {
    "initial": [
      "Race",
      "Ring",
      "Rose",
      "Rat",
      "Rake",
      "Rabbit",
      "Raccoon",
      "Robot",
      "Raincoat",
      "Roof",
    ],
    "median": [
      "Cereal",
      "Parents",
      " Syrup",
      "Dictionary",
      "Orange",
      "Cherries",
      "Parrot",
      "Carrot",
      "Camera",
      "Zero",
    ],
    "final": [
      "Star",
      " Chair",
      "Baker",
      " Flower",
      "Spider",
      "Four",
      "Door",
      "Hair",
      "Tier",
      "Butter",
    ]
  },
  "r": {
    "initial": [
      "Farm",
      "Heart",
      "Alarm",
      "Birds",
      "Nurse",
      "Girl",
      "Turn",
      "Fork",
      "Corn",
      "Bored",
    ],
    // "median": [67, 65, 54, 33, 44, 55],
    // "final": [
    //   223,
    //   344,
    //   556,
    //   677,
    //   788,
    // ]
  },
  "s": {
    "initial": [
      "Soup",
      "Sing",
      "Seeds",
      "Socks",
      "Soap",
      "Sad",
      "Seven",
      "Sand",
      "Sofa",
      "Suit",
    ],
    "median": [
      "Pasta",
      "Blossom",
      "Fossil",
      "Baseball",
      "Ice cream",
      "Listen",
      "Pencil",
      "Castle",
      "Popsicle",
      "Dancing",
    ],
    "final": [
      "Goose",
      "Floss",
      "Vase",
      "Bus",
      "Juice",
      "Police",
      "Mice",
      "Face",
      "Moose",
      "Tennis",
    ]
  },
  "sh": {
    "initial": [
      "Shoes",
      "Shout,",
      "Shy",
      "Shiny",
      "Shopping",
      "Sugar",
      "Shadow",
      "Shampoo",
      "Shapes",
      "Sheep",
    ],
    "median": [
      "Cushions",
      "Rushing",
      "Push Up",
      "Dishes",
      "Handshake",
      "windshield",
      "Graduation",
      "Brushing",
      "Mushroom",
      "Flu Shot",
    ],
    "final": [
      "Fish",
      "Crash",
      "Wash",
      "Hairbrush",
      "Rash",
      "Splash",
      "Flash",
      "Dish",
      "Trash",
      "Leash",
    ],
  },
  "t": {
    "initial": [
      "Teacher",
      "Tent",
      "Tissue",
      "Toy Car",
      "Toes",
      "Tennis",
      "Tie",
      "Tacos",
      "Table",
      "Tongue",
    ],
    "median": [
      "Kitten",
      "Pants",
      "Potatoes",
      "Guitar",
      "Tomatoes",
      "Pointing",
      "Mustard",
      "Basketball",
      "Cantaloupe",
      "Vegetable"
    ],
    "final": [
      "Toast",
      "Goat",
      "Suit",
      "Feet",
      "Pot",
      "Hat",
      "Ant",
      "Basket",
      "Doughnut",
      "Chocolate",
    ]
  },
  "v": {
    "initial": [
      "Voice",
      "Van",
      "Vacuum",
      "Vase",
      "Vest",
      "Visit",
      "Vampire",
      "Visor",
      "Vehicle",
      "Vacation"
    ],
    "median": [
      "Heavy",
      "Raven",
      "Saving",
      "Avocado",
      "Oven",
      "Fever",
      "River",
      "SkyDiving",
      "Seven",
      "Oval"
    ],
    "final": [
      "Five",
      "Five",
      "Leave",
      "Drive",
      "Give",
      "Wave",
      "Save",
      "Stove",
      "Sleeve",
      "Love"
    ]
  },
  "w": {
    "initial": [
      "Wolf",
      "Wave",
      "Wheelchair",
      "Wig",
      "Worm",
      "Working",
      "Window",
      "Watch",
      "Walking",
      "Window"
    ],
    "median": [
      "Sandwich",
      "Microwave",
      "Chewing",
      "Mouthwash",
      "Kiwi",
      "Halloween",
      "Shower",
      "Twenty",
      "Oneway",
      "Rowing"
    ],
    "final": [
      "Cow",
      "Bow",
      "Row",
      "Yellow",
      "Show",
      "Snow",
      "Blow",
      "Crow",
      "Dough",
      "Throw"
    ]
  },
  "y": {
    "initial": [
      "Yellow",
      "Yo-Yo",
      "Yam",
      "Yacht",
      "Yogurt",
      "Yelling",
      "Yes",
      "Yummy",
      "Young",
      "Yawn"
    ],
    "median": [
      "Bye-bye",
      "Rainbow",
      "Rice",
      "Kayak",
      "Playground",
      "Flight",
      "Crayons",
      "Recycle",
      "Praying",
      "Layer",
    ],
    "final": [
      "Boy",
      "Dry",
      "Shy",
      "Spy",
      "Spray",
      "Sky",
      "Fry",
      "Fly",
      "Cry",
      "May"
    ]
  },
  "z": {
    "initial": [
      "Cheese",
      "Eyes",
      "Pillows",
      "Exercises",
      "Keys",
      "Tomatoes",
      "Scissors",
      "Shoes",
      "Prize",
      "Cherries"
    ],
    "median": [
      "Lizard",
      "Present",
      "Cheesecake",
      "Raisins",
      "Dessert",
      "Eraser",
      "Pizza",
      "Lasagna",
      "Crazy",
      "Hazelnut"
    ],
    "final": [
      "Cheese",
      "Eyes",
      "Pillows",
      "Exercises",
      "Keys",
      "Tomatoes",
      "Scissors",
      "Shoes",
      "Prize",
      "Cherries"
    ]
  },
  "l-": {
    "initial": [
      "Gloves",
      "Glasses",
      "Flute",
      "Flowers",
      "Flag",
      "Flashlight",
      "Blow dry",
      "Flamingo"
          "Blanket"
          "Plant"
      // "median": [67, 65, 54, 33, 44, 55],
      // "final": [
      //   223,
      //   344,
      //   556,
      //   677,
      //   788,
    ]
  },
  "R-": {
    "initial": [
      "Fruits",
      "Breakfast",
      "Groom",
      "Grey",
      "Drink",
      "friends",
      "Bridge",
      "Bracelet",
      "Broom",
      "Broccoli",
    ],
    // "median": [67, 65, 54, 33, 44, 55],
    // "final": [
    //   223,
    //   344,
    //   556,
    //   677,
    //   788,
    // ]
  },
  "S-": {
    "initial": [
      "Skateboard",
      "Stairs",
      "Starfish",
      "Scarf",
      "Star",
      "Spaghetti",
      "Scorpion",
      "Sponge",
      "Skirt"
          "Slippers"
    ],
    // "median": [67, 65, 54, 33, 44, 55],
    // "final": [
    //   223,
    //   344,
    //   556,
    //   677,
    //   788,
    // ]
  },
};


